'use client'

import { Document, Page, Text, View, StyleSheet, PDFDownloadLink } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
    paddingBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1a1a1a',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 12,
    color: '#666',
  },
  section: {
    marginBottom: 25,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
  },
  description: {
    fontSize: 11,
    color: '#444',
    lineHeight: 1.6,
  },
  table: {
    marginTop: 10,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f3f4f6',
    padding: 10,
    borderTopWidth: 1,
    borderTopColor: '#e5e5e5',
  },
  tableRow: {
    flexDirection: 'row',
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
  },
  tableCell: {
    fontSize: 10,
    color: '#333',
  },
  col1: { width: '50%' },
  col2: { width: '25%', textAlign: 'right' },
  col3: { width: '25%', textAlign: 'right' },
  totalRow: {
    flexDirection: 'row',
    padding: 12,
    backgroundColor: '#f9fafb',
    marginTop: 10,
  },
  totalLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  totalAmount: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#1a1a1a',
    textAlign: 'right',
    flex: 1,
  },
  footer: {
    marginTop: 40,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#e5e5e5',
    fontSize: 9,
    color: '#888',
    textAlign: 'center',
  },
})

interface PlanMilestone {
  label: string
  amount: number
  dueDate?: string
}

interface PlanPDFProps {
  projectTitle: string
  description?: string | null
  milestones: PlanMilestone[]
  currency?: string
}

export function PlanPDFDocument({ projectTitle, description, milestones, currency = 'USD' }: PlanPDFProps) {
  const total = milestones.reduce((sum, m) => sum + (m.amount || 0), 0)
  const currencySymbol = currency === 'USD' ? '$' : currency

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{projectTitle}</Text>
          <Text style={styles.subtitle}>Project Plan</Text>
        </View>

        {description && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Project Description</Text>
            <Text style={styles.description}>{description}</Text>
          </View>
        )}

        {milestones.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Milestones</Text>
            <View style={styles.table}>
              <View style={styles.tableHeader}>
                <Text style={[styles.tableCell, styles.col1]}>Deliverable</Text>
                <Text style={[styles.tableCell, styles.col2]}>Due Date</Text>
                <Text style={[styles.tableCell, styles.col3]}>Amount</Text>
              </View>
              {milestones.map((m, i) => (
                <View key={i} style={styles.tableRow}>
                  <Text style={[styles.tableCell, styles.col1]}>{m.label}</Text>
                  <Text style={[styles.tableCell, styles.col2]}>
                    {m.dueDate ? new Date(m.dueDate).toLocaleDateString() : 'TBD'}
                  </Text>
                  <Text style={[styles.tableCell, styles.col3]}>
                    {currencySymbol}{m.amount.toLocaleString()}
                  </Text>
                </View>
              ))}
              <View style={styles.totalRow}>
                <Text style={styles.totalLabel}>Total</Text>
                <Text style={styles.totalAmount}>
                  {currencySymbol}{total.toLocaleString()}
                </Text>
              </View>
            </View>
          </View>
        )}

        <View style={styles.footer}>
          <Text>Generated by Tayseer</Text>
        </View>
      </Page>
    </Document>
  )
}

interface DownloadPlanPDFProps {
  projectTitle: string
  description?: string | null
  milestones: PlanMilestone[]
  currency?: string
  filename?: string
}

export function DownloadPlanPDF({ 
  projectTitle, 
  description, 
  milestones, 
  currency,
  filename 
}: DownloadPlanPDFProps) {
  return (
    <PDFDownloadLink
      document={
        <PlanPDFDocument
          projectTitle={projectTitle}
          description={description}
          milestones={milestones}
          currency={currency}
        />
      }
      fileName={filename || `${projectTitle.toLowerCase().replace(/\s+/g, '-')}-plan.pdf`}
      className="flex items-center gap-2 px-3 py-1.5 bg-white/5 text-slate-300 rounded-md hover:bg-white/10 text-sm font-medium transition-colors"
    >
      {({ loading }) => (loading ? 'Generating...' : 'Download PDF')}
    </PDFDownloadLink>
  )
}